#!/usr/bin/env bash
# shellcheck disable=SC2086,SC2102
# Quotes and aws command do not mix well
# shellcheck source=./aws.functions
source ${0%/*}/aws.functions
# shellcheck source=./ecLaunch.vars
VARS=${0%/}.vars
source $VARS
if [[ -e $VARS.local ]] ; then
  source $VARS.local
fi
if [[ -e $HOME/.aws-tools/${VARS##*/}.local ]] ; then
  source $HOME/.aws-tools/${VARS##*/}.local
fi

# Usage output
usage() {
  echo "Usage: ${BASH_SOURCE[0]} [ -t | --type INSTANCETYPE ] [ -o | --owner OWNERTAG ] [ -p | --project PROJECT] [ -a | --ami AMI ]
        If unspcified:
        INSTANCETYPE is r5d.large
        OWNERTAG is iam user
        AMI is the default Amazon Linux AMI"
  exit 2
}

# Get viable subnets (zones)
subnets=$(aws ec2 describe-subnets --filters "Name=tag:vpc,Values=default" "Name=tag:subnet,Values=private" --query "Subnets[*].SubnetId")
networkNumber=$((1 + $RANDOM % 3))
counter=0
for subnet in $subnets ; do
  counter=$((counter = counter + 1))
  if [[ $counter -eq $networkNumber ]] ; then
    break
  fi
done

# A Hack for MacOS incompatible getop
if command -v sw_vers ; then 
	if [[ $(sw_vers -productName) == macOS ]] ; then
		if [[ -d /usr/local/opt/gnu-getopt/bin ]] ; then
      # for Intel Mac
			PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
  	elif [[ -d /opt/homebrew/opt/gnu-getopt/bin ]] ; then
      # For Apple Silcon Mac
      PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"
    else
    	echo you need to install gnu getopt
    	exit 1
  	fi
	fi
fi

# Get and check parameters
ARGS=$(getopt --name ec2launch \
              --options 't:o:p:a:' \
              --longoptions 'type:,owner:,project:,ami:' -- "$@")

VALID_ARGUMENTS="$?"
if [[ "$VALID_ARGUMENTS" -gt "0" ]]; then
  usage
fi
eval "set -- $ARGS"
while true; do
    case $1 in
      -t|--type)
            INSTANCETYPE=${2}; shift 2;;
      -o|--owner)
            OWNERTAG=$2; shift 2;;
      -p|--project)
            PROJECT=$2; shift 2;;
      -a|--ami)
            IMAGEID=$2; shift 2;;
      --)  shift; break;;
      *)   echo "option $1 is unknown" ; usage; exit 1;;           # error
    esac
done

# Get IAM user          
if [[ -z $OWNERTAG ]] ; then
  OWNERTAG=$(runAwsCommand iam get-user \
            --output text \
            --query User.UserName)
fi
# Get Requested instance information:
while read -r Architecture vcpu Memory StorageTotal StorageDiskSize StorageDiskCount StorageDiskNVME GPU_Manufacturer GPU_Name GPU_Number GPU_Memory FPGA_Manufacturer FPGA_Name FPGA_Number FPGA_Memory INF_Manufacturer INF_Name INF_Number SupportedVirtualizationType ; do

  echo "Requested $Architecture Instance with $vcpu vCPU, $Memory Memory"
  if [[ $StorageDiskCount -gt 0 ]] ; then
    echo "The $INSTANCETYPE has $StorageDiskCount x $StorageDiskSize GB disks, Total of $StorageTotal of instance storage, NVME is $StorageDiskNVME"
    for ((disk = 1 ; disk <= StorageDiskCount ; disk++)); do
      printf -v DiskLetter "\x$(printf %x $((${disk}+97)))"
      ephemeral=$((disk - 1))
      if [[ $disk -eq 1 ]] ; then
        DiskMapping="DeviceName=/dev/sd$DiskLetter,VirtualName=ephemeral$ephemeral"
      elif [[ $disk -gt 1 ]] ; then
        DiskMapping="$DiskMapping DeviceName=/dev/sd$DiskLetter,VirtualName=ephemeral$ephemeral"
      fi
    done 
      extraParams="--block-device-mappings $DiskMapping"
  else
    echo "The $INSTANCETYPE has has no instance storage"
  fi

  excelerator="None"
  if [[ $GPU_Manufacturer != "None" ]] ; then
    excelerator="$GPU_Manufacturer"
    echo "and $GPU_Number $GPU_Manufacturer $GPU_Name and $GPU_Memory Memory"
  elif [[ $FPGA_Manufacturer != "None" ]]; then
    excelerator="FPGA"
    echo "and $FPGA_Number $FPGA_Manufacturer $FPGA_Name and $FPGA_Memory Memory"
  elif [[ $INF_Manufacturer != "None" ]]; then
    excelerator="Inference"
    echo "and $FPGA_Number $INF_Number $INF_Name"
  else
    excelerator="None"
  fi

  ## Get AMI
  case $Architecture in
    i386 | x86_64)
      case $excelerator in
        NVIDIA | Inference)
          ## For accelerated see https://aws.amazon.com/releasenotes/aws-deep-learning-ami-catalog/
          IMAGEID=$(runAwsCommand ec2 describe-images \
            --owners amazon \
            --filters 'Name=name,Values=Deep?Learning?Base?AMI?(Amazon?Linux?2)?Version???.?' "Name=state,Values=available" \
            --query "reverse(sort_by(Images,&CreationDate))[:1].ImageId" --output text)
          ;;      
        None)
          IMAGEID=$(runAwsCommand ec2 describe-images \
            --owners amazon \
            --filters "Name=name,Values=amzn2-ami-$SupportedVirtualizationType-2.0.????????.?-$Architecture-gp2" "Name=state,Values=available" \
            --query "reverse(sort_by(Images,&CreationDate))[:1].[ImageId]")
          ;;
        *)
          echo "No support for $excelerator on $Architecture yet, exiting"
          exit 0
          ;;
      esac
      ;;
    arm64)
      case $excelerator in
        NVIDIA)
          IMAGEID=$(runAwsCommand ec2 describe-images \
            --owners amazon \
            --filters "Name=name,Values=Deep Learning AMI*" "Name=state,Values=available" \
            --query 'reverse(sort_by(Images,&CreationDate))[:1].[ImageId]')
          ;;
        None)
          IMAGEID=$(runAwsCommand ec2 describe-images \
            --owners amazon \
            --filters "Name=name,Values=amzn2-ami-$SupportedVirtualizationType-2.0.????????.?-$Architecture-gp2" 'Name=state,Values=available' \
            --query 'reverse(sort_by(Images,&CreationDate))[:1].[ImageId]')
          ;;
        *)
          echo "No support for $excelerator on $Architecture yet, exiting"
          exit 0
          ;;
      esac
      ;;
    x86_64_mac)
      echo "No Support for Mac X64 yet, exiting"
      exit 0
      ;;
    *)
      echo "Unknown architecture, exiting"
      exit 0
      ;;
  esac

done < <(aws --output text ec2 describe-instance-types --instance-types $INSTANCETYPE \
    --query InstanceTypes[].[ProcessorInfo.SupportedArchitectures[0],VCpuInfo.DefaultVCpus,MemoryInfo.SizeInMiB,InstanceStorageInfo.TotalSizeInGB,InstanceStorageInfo.Disks[0].SizeInGB,InstanceStorageInfo.Disks[0].Count,InstanceStorageInfo.NvmeSupport,GpuInfo.Gpus[0].Manufacturer,GpuInfo.Gpus[0].Name,GpuInfo.Gpus[0].Count,GpuInfo.TotalGpuMemoryInMiB,FpgaInfo.Fpgas[0].Manufacturer,FpgaInfo.Fpgas[0].Name,FpgaInfo.Fpgas[0].Count,FpgaInfo.TotalFpgaMemoryInMiB,InferenceAcceleratorInfo.Accelerators[0].Manufacturer,InferenceAcceleratorInfo.Accelerators[0].Name,InferenceAcceleratorInfo.Accelerators[0].Count,SupportedVirtualizationTypes[0]])

if [[ -n $LAUNCHTEMPLATEVERSION ]]; then
  LAUNCHTEMPLATEVERSION=",Version=$LAUNCHTEMPLATEVERSION"
fi


InstanceID=$(aws ec2 run-instances $extraParams \
  --launch-template LaunchTemplateId=${LAUNCHTEMPLATE}${LAUNCHTEMPLATEVERSION} \
  --image-id $IMAGEID \
  --instance-type $INSTANCETYPE \
  --subnet-id $subnet --security-groups "EC2" --no-associate-public-ip-address \
  --tag-specifications \
  	"ResourceType=instance,Tags=[{Key=Name,Value=$NAMEPREFIX-$OWNERTAG},{Key=Creator,Value=$OWNERTAG},{Key=Owner,Value=$OWNERTAG},{Key=Project,Value=$PROJECT}$MORETAGS]" \
  	"ResourceType=volume,Tags=[{Key=Name,Value=$NAMEPREFIX-$OWNERTAG},{Key=Owner,Value=$OWNERTAG},{Key=Project,Value=$PROJECT}$MORETAGS]" \
  --query Instances[*].[InstanceId] )

echo "Launching Image $IMAGEID as Instance $InstanceID"

